# fly.toml app configuration file generated for psifoperma on 2023-05-07T18:15:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "psifoperma"
kill_signal = "SIGINT"
kill_timeout = 10
primary_region = "fra"
processes = []

[build]

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "60s"
    interval = "20s"
    restart_limit = 3
    timeout = "20s"
